#!/usr/bin/env python
"""ReMIX-B results -> LaTeX table for the paper.

  python scripts/remixb_table.py results/remix_b/music4all/results.json \
      --out paper/tables/remixb_results.tex

Rows are grouped by baseline family; the best non-oracle score per column is bold.
Baselines missing from results.json are skipped.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

GROUPS = [
    ("Reference", [("random", "Random"), ("target_caption_oracle", "Target-caption oracle$^\\dagger$")]),
    ("Seed only", [("seed_audio_nn", "Seed audio NN"), ("seed_caption_nn", "Seed caption NN")]),
    ("Instruction only", [("instruction_text", "Instruction text")]),
    ("Composed, no training", [("bm25", "BM25 (caption + instr.)"), ("caption_plus_instruction", "Caption + instruction"),
                               ("mulan_zeroshot", "MuLan zero-shot"), ("late_fusion", "Late fusion")]),
    ("LLM-assisted", [("llm_caption_rewrite", "LLM caption rewrite"), ("mulan_rewrite", "MuLan rewrite"),
                      ("analogy_steering", "Analogy steering"), ("hybrid_score_fusion", "Hybrid score fusion"),
                      ("llm_pointwise_rerank", "LLM pointwise rerank")]),
    ("Trained on ReMIX", [("remix_c_untrained", "ReMIX-C, untrained"), ("remix_c", "ReMIX-C (2-layer fusion)"),
                          ("remix_c_d4", "ReMIX-C (4-layer fusion)"), ("remix_c_unfiltered", "ReMIX-C (unfiltered data)")]),
]
COLS = [("nDCG@10", "nDCG@10"), ("nDCG@100", "nDCG@100"), ("AP(rel=3)", "MAP"),
        ("R(rel=3)@10", "R@10"), ("R(rel=3)@100", "R@100"), ("RR(rel=3)", "MRR")]
NOT_RANKED = {"target_caption_oracle"}  # uses the answer; excluded from "best"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("results")
    ap.add_argument("--out", default="paper/tables/remixb_results.tex")
    a = ap.parse_args()
    res = json.loads(Path(a.results).read_text())
    best = {k: max(v["metrics"][k] for n, v in res.items() if n not in NOT_RANKED) for k, _ in COLS}
    lines = ["% Auto-generated by scripts/remixb_table.py", "\\begin{tabular}{l" + "c" * len(COLS) + "r}",
             "\\toprule", "Method & " + " & ".join(c for _, c in COLS) + " & TFLOP \\\\", "\\midrule"]
    first = True
    for group, rows in GROUPS:
        rows = [(k, name) for k, name in rows if k in res]
        if not rows:
            continue
        if not first:
            lines.append("\\midrule")
        first = False
        lines.append(f"\\multicolumn{{{len(COLS) + 2}}}{{l}}{{\\textit{{{group}}}}} \\\\")
        for k, name in rows:
            m = res[k]["metrics"]
            cells = [(f"\\textbf{{{m[c]:.3f}}}" if k not in NOT_RANKED and m[c] == best[c] else f"{m[c]:.3f}")
                     for c, _ in COLS]
            tf = res[k].get("tflops", 0.0)
            lines.append(f"\\quad {name} & " + " & ".join(cells) + f" & {tf:,.0f} \\\\" if tf >= 1
                         else f"\\quad {name} & " + " & ".join(cells) + " & $<$1 \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    Path(a.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {a.out} ({sum(1 for _, r in GROUPS for k, _ in r if k in res)} baselines)")


if __name__ == "__main__":
    main()
